version: '3.8'

services:
  app:
    image: ghcr.io/buzz-code/wolf-student-report:latest
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
      - APP_HOST=0.0.0.0
      - DB_CLIENT=${DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_DEBUG=${DB_DEBUG}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
    ports:
      - "3111:3000"
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.labels.listenReport == true
